
language: python

before_install:
  - sudo apt-get install freeglut3-dev
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script:
  python3 -m pytest

notifications:
  email:
    on_success: always
    on_failure: always
