
language: python

branches:
  only:
    - dev-eaglemango

script:
  python3 -m pytest

notifications:
  email:
    recipients:
      - eaglemango@gmail.com
    on_success: always
    on_failure: always