
language: python

branches:
  only:
    - dev-eaglemango

before_install:
  - sudo apt-get install freeglut3-dev

script:
  python3 -m pytest

notifications:
  email:
    on_success: always
    on_failure: always