language: python
python:
  - "3.6"

notifications:
  email:
    on_success: always
    on_failure: always


branches:
  only:
    - dev-artyomnurgaliev
install:
  - pip install -r requirements.txt

script:
  python3 -m pytest