
language: python

env:
  - DISPLAY=:99.0

before_install:
  - sudo apt-get install freeglut3-dev
  - sh -e /etc/init.d/xvfb start




script:
  python3 -m pytest

notifications:
  email:
    on_success: always
    on_failure: always
