
language: python
before_install:
  - sudo apt-get install freeglut3-dev
  - sh -e /etc/init.d/xvfb start
  - "export DISPLAY=:99.0"

install:
  - pip install -r requirements.txt
  - pip install -e hg+https://pyglet.googlecode.com/hg/@2813:0aa8bfe3313a#egg=pyglet

script:
  python3 -m pytest

notifications:
  email:
    on_success: always
    on_failure: always
