
language: python

before_install:
  - sudo apt-get install freeglut3-dev

install:
  - pip install -r requirements.txt

script:
  python3 -m pytest

notifications:
  email:
    on_success: never
    on_failure: never