
language: python

addons:
  apt:
    packages:
      - xvfb
env:
  global:
    - DISPLAY=:99

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
  - sleep 3

script:
  python3 -m pytest

notifications:
  email:
    on_success: always
    on_failure: always
