
language: python
before_install:
  - sudo apt-get install freeglut3-dev
  - sh -e /etc/init.d/xvfb start
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - "pip install --upgrade http://pyglet.googlecode.com/archive/tip.zip"
  - pip install -r requirements.txt

script:
  python3 -m pytest

notifications:
  email:
    on_success: always
    on_failure: always
