language: python

python:
  - "3.6"

before_script:
  - sudo apt-get update
  - sudo apt-get install build-essential
  - sudo apt-get install freeglut3-dev
  - pip install setuptools

install:
  - pip install --upgrade pytest
  - pip install -r requirements.txt

script:
  python3 -m pytest

deploy:
   provider: pypi
   user: $USERNAME
   password: $PASSWORD
#   distributions: "bdist_wheel"

after_success:
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: never