language: python

python:
  - "3.6"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - pip install setuptools
  - pip uninstall pyglet
  - apt-get install python-pyglet
install:
  - pip install --upgrade pytest
  - pip install -r requirements.txt

script:
  python3 -m pytest

deploy:
   provider: pypi
   user: $USERNAME
   password: $PASSWORD
   distributions: "bdist_wheel"

after_success:
  - coveralls





notifications:
  email:
    on_success: never
    on_failure: never